"""
ForgeHub AI — Deterministic Mock LLM Provider
Returns pre-baked, valid dbt SQL for each demo dataset.
Also supports 'broken' mode to trigger hallucination failure demonstration.
"""
from __future__ import annotations

import json

from app.llm.base import LLMProvider

# ─── Pre-baked correct artifacts ─────────────────────────────────────────────

_ORDERS_SQL = """\
WITH orders AS (

    SELECT
        order_id,
        customer_id,
        order_date,
        quantity,
        unit_price,
        status
    FROM {{ source('retail', 'orders') }}

),

final AS (

    SELECT
        order_id,
        customer_id,
        order_date,
        status,
        quantity,
        unit_price,
        quantity * unit_price AS order_value
    FROM orders

)

SELECT * FROM final
"""

_ORDERS_SCHEMA = """\
version: 2

sources:
  - name: retail
    tables:
      - name: orders

models:
  - name: fct_orders
    description: "Fact table for customer orders. One row per order. Generated by ForgeHub AI."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to the customers table."
        tests:
          - not_null
      - name: order_date
        description: "Date the order was placed."
        tests:
          - not_null
      - name: status
        description: "Order fulfillment status."
        tests:
          - not_null
      - name: quantity
        description: "Number of units ordered."
        tests:
          - not_null
      - name: unit_price
        description: "Price per unit at time of order. WARNING: Currency undefined in metadata."
      - name: order_value
        description: "Computed order value (quantity * unit_price). Currency undefined — treat with caution."
"""

_CUSTOMERS_SQL = """\
WITH customers AS (

    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        country_code,
        signup_date
    FROM {{ source('retail', 'customers') }}

),

final AS (

    SELECT
        customer_id,
        CONCAT(first_name, ' ', last_name)  AS full_name,
        LOWER(TRIM(email))                   AS clean_email,
        country_code,
        signup_date
    FROM customers

)

SELECT * FROM final
"""

_CUSTOMERS_SCHEMA = """\
version: 2

sources:
  - name: retail
    tables:
      - name: customers

models:
  - name: dim_customers
    description: "Customer dimension table. One row per customer. Generated by ForgeHub AI."
    columns:
      - name: customer_id
        description: "Unique customer identifier."
        tests:
          - unique
          - not_null
      - name: full_name
        description: "Derived full name (first_name + last_name). PII."
      - name: clean_email
        description: "Normalized lowercase email. PII."
      - name: country_code
        description: "Country code. WARNING: Semantic type undefined in metadata."
      - name: signup_date
        description: "Date the customer registered."
        tests:
          - not_null
"""

_REVENUE_SQL = """\
WITH revenue AS (

    SELECT
        order_date,
        gross_revenue,
        COALESCE(discount_amount, 0) AS discount_amount,
        discount_rate,
        order_count
    FROM {{ source('retail', 'revenue') }}

),

monthly AS (

    SELECT
        DATE_TRUNC(order_date, MONTH)              AS month,
        SUM(gross_revenue)                          AS total_gross_revenue,
        SUM(discount_amount)                        AS total_discounts,
        SUM(gross_revenue - discount_amount)        AS net_revenue,
        AVG(discount_rate)                          AS avg_discount_rate,
        SUM(order_count)                            AS total_orders
    FROM revenue
    GROUP BY 1

)

SELECT * FROM monthly
"""

_REVENUE_SCHEMA = """\
version: 2

sources:
  - name: retail
    tables:
      - name: revenue

models:
  - name: monthly_revenue
    description: "Monthly revenue cohort aggregation. One row per month. Generated by ForgeHub AI."
    columns:
      - name: month
        description: "First day of the calendar month."
        tests:
          - unique
          - not_null
      - name: total_gross_revenue
        description: "Sum of gross revenue. WARNING: Currency ambiguous in metadata."
      - name: total_discounts
        description: "Sum of promotional discounts applied."
      - name: net_revenue
        description: "Gross revenue minus discounts."
      - name: avg_discount_rate
        description: "Average discount rate (decimal). Derived from percentage column — not summed."
      - name: total_orders
        description: "Total number of orders in the month."
        tests:
          - not_null
"""

# ─── Broken (hallucination) outputs ──────────────────────────────────────────

_BROKEN_SQL = """\
SELECT
    customer_name,
    fake_revenue,
    invented_metric
FROM retail.orders
"""

_BROKEN_SCHEMA = """\
version: 2

models:
  - name: fct_orders
    columns:
      - name: customer_name
        description: "Customer name."
      - name: fake_revenue
        description: "Revenue field."
      - name: invented_metric
        description: "Some metric."
"""

# ─── README templates ─────────────────────────────────────────────────────────

def _make_readme(model_name: str, source: str, grain: str) -> str:
    return f"""# {model_name}

## Model Overview
Generated by **ForgeHub AI** — metadata-aware dbt model generation.

## Source Datasets
- `{source}`

## Model Grain
{grain}

## Generation Provenance
- **LLM Provider**: Mock (deterministic demo)
- **Metadata Source**: DataHub
- **Validated**: SQL AST ✓ | Semantic Rules ✓ | dbt Schema ✓

> All transformations are derived from verified DataHub metadata.
> Fields marked WARNING have metadata gaps that should be resolved before production use.
"""


# ─── Mock dispatch ────────────────────────────────────────────────────────────

_DATASET_ARTIFACTS: dict[str, dict[str, str]] = {
    "orders": {
        "sql": _ORDERS_SQL,
        "schema_yml": _ORDERS_SCHEMA,
        "readme": _make_readme("fct_orders", "retail.orders", "One row per order (order_id)"),
    },
    "customers": {
        "sql": _CUSTOMERS_SQL,
        "schema_yml": _CUSTOMERS_SCHEMA,
        "readme": _make_readme("dim_customers", "retail.customers", "One row per customer (customer_id)"),
    },
    "revenue": {
        "sql": _REVENUE_SQL,
        "schema_yml": _REVENUE_SCHEMA,
        "readme": _make_readme("monthly_revenue", "retail.revenue", "One row per calendar month"),
    },
}

_BROKEN_ARTIFACTS: dict[str, str] = {
    "sql": _BROKEN_SQL,
    "schema_yml": _BROKEN_SCHEMA,
    "readme": "# Broken Model\n\nThis output was intentionally hallucinated for the failure demo.",
}


class MockProvider(LLMProvider):
    """
    Deterministic mock LLM provider.
    Returns pre-baked artifacts — no API keys required.
    Set broken=True to return hallucinated SQL for the failure demo.
    """

    def __init__(self, dataset_id: str = "orders", broken: bool = False) -> None:
        self._dataset_id = dataset_id
        self._broken = broken

    def generate(self, prompt: str) -> str:
        """
        Return a JSON-serialised artifact dict.
        The generation agent will extract sql / schema_yml / readme from this.
        """
        if self._broken:
            return json.dumps(_BROKEN_ARTIFACTS)

        artifacts = _DATASET_ARTIFACTS.get(self._dataset_id)
        if artifacts is None:
            # Fallback to orders for unknown datasets
            artifacts = _DATASET_ARTIFACTS["orders"]
        return json.dumps(artifacts)

    @property
    def name(self) -> str:
        return "mock"
